[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "db-schema-guard"
version = "0.1.1"
description = "Stop silent schema drift before it breaks your data pipelines"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Anil Solanki", email = "anusolanki2645@gmail.com"}
]
keywords = ["data-engineering", "schema", "ci-cd", "postgresql"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "click>=8.0",
    "pyyaml>=6.0",
    "sqlalchemy>=1.4",
    "psycopg2-binary",
    "python-dotenv",
    "jinja2>=3.0",
]

[project.optional-dependencies]
snowflake = ["snowflake-sqlalchemy>=1.5"]
sqlserver = ["pymssql>=2.2"]
oracle = ["oracledb>=1.0"]
databricks = ["databricks-sql-connector>=2.0", "databricks-sqlalchemy>=1.0"]
all = [
    "snowflake-sqlalchemy>=1.5",
    "pymssql>=2.2",
    "oracledb>=1.0",
    "databricks-sql-connector>=2.0",
    "databricks-sqlalchemy>=1.0",
]
dev = ["pytest>=7.0"]

[project.scripts]
schema-guard = "schema_guard.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]