name: Secret Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        run: |
          if [ -z "$MY_DB" ]; then
            echo "Secret is EMPTY"
            exit 1
          else
            echo "Secret length: ${#MY_DB}"
          fi
        env:
          MY_DB: ${{ secrets.TEST_DB }}